steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "southamerica-east1-docker.pkg.dev/microservices-490221/image-registry/payments",
        "-f",
        "dockerfile.prod",
        "--platform=linux/amd64",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "southamerica-east1-docker.pkg.dev/microservices-490221/image-registry/payments",
      ]
options:
  logging: CLOUD_LOGGING_ONLY